### PR TITLE
Update version of curator

### PR DESCRIPTION
**Pull request by Alykoff**
Change version of `curator` framework for compatibility with newest versions of `zookeeper`

### CODE REVIEW

**Comment by mesutcelik** [comment]
verify

**Comment by mesutcelik** [comment]
Thanks for the contribution @Alykoff !

I know it is a small bit but we still need CLA. Can you please sign?
https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement

**Comment by mesutcelik** [comment]
@jerrinot feel free to merge it when you receive CLA.

**Comment by jerrinot** [comment]
@Alykoff: Unfortunately I can't the agreement from you. When did you send it?

**Comment by Alykoff** [comment]
@jerrinot: I send the email in 28 Feb 2018 using this email address: jaromir AT hazelcast.com.
Today I also send the second email.

Could you please check the mail again?

**Comment by jerrinot** [comment]
@Alykoff: I can confirm I received the CLA today. Thanks for your contribution!

**Pull request merged**
