### PR TITLE
Cleanups and bug fixes.

### PR DESCRIPTION
**Pull request by kobalski**
-Added necessary hooks under META-INF folder
-Renamed packages
-Fixed NPE when used with clients.
-Right now code is published to bintray, we should make necessary changes for official release.

### CODE REVIEW

**Comment by jbaruch** [comment]
You know that you can sync from Bintray to Maven Central with a one click (or one REST API call), right?

**Comment by kobalski** [comment]
Yeah, I know. Best tool I have ever used for distribution, but I think we use our own server and scripts (which I do not know much) to publish to Maven Central. So I will let people who are experts on relase decide.

**Comment by jbaruch** [comment]
Let me talk to those people! :D

**Comment by gAmUssA** [comment]
@bilalyasar do you want talk to @jbaruch about releasing to maven central via Bintray?

**Pull request merged**
